modLoader="javafml"
loaderVersion="[48,)"
license="MIT License"
[[mods]]
modId="harderfarthergrimcitadels"
version="${file.jarVersion}"
displayName="Harder Farther Grim Citadels"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lootcontrolutility"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='Harder Farther Grim Citadels.'
[[dependencies.harderfarthergrimcitadels]]
    modId="forge"
    mandatory=true
    versionRange="[48,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.harderfarthergrimcitadels]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2,1.21)"
    ordering="NONE"
    side="BOTH"

